services:
  - type: web
    name: nasf-tec
    env: static
    plan: free
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
